// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdocqrnaorvwgprdzdkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkb2Nxcm5hb3J2d2dwcmR6ZGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzY1OTYsImV4cCI6MjA3MDYxMjU5Nn0.zVmPRoJmQnBDTBDqyPNtr4Oi2I0YQG49sdF5FVojxtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});